# Generated by Django 3.0.8 on 2020-07-17 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePage',
            new_name='Page',
        ),
    ]
