# Generated by Django 3.0.8 on 2020-07-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200717_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
