# Generated by Django 3.0.8 on 2020-07-14 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('cell', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_start_date', models.DateField()),
                ('schedule_end_date', models.DateField()),
                ('monday_time_block', models.FloatField()),
                ('monday_start', models.TimeField()),
                ('monday_end', models.TimeField(null=True)),
                ('tuesday_time_block', models.FloatField()),
                ('tuesday_start', models.TimeField(null=True)),
                ('tuesday_end', models.TimeField(null=True)),
                ('wednesday_time_block', models.FloatField()),
                ('wednesday_start', models.TimeField(null=True)),
                ('wednesday_end', models.TimeField(null=True)),
                ('thursday_time_block', models.FloatField()),
                ('thursday_start', models.TimeField(null=True)),
                ('thursday_end', models.TimeField(null=True)),
                ('friday_time_block', models.FloatField()),
                ('friday_start', models.TimeField(null=True)),
                ('friday_end', models.TimeField(null=True)),
                ('saturday_time_block', models.FloatField()),
                ('saturday_start', models.TimeField(null=True)),
                ('saturday_end', models.TimeField(null=True)),
                ('sunday_time_block', models.FloatField()),
                ('sunday_start', models.TimeField(null=True)),
                ('sunday_end', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haircut_adult', models.FloatField()),
                ('haricut_teen', models.FloatField()),
                ('haircut_child', models.FloatField()),
                ('shave', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_res', to='shop.Customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_res', to='shop.Service')),
            ],
            options={
                'ordering': ('-start',),
            },
        ),
    ]
