# Generated by Django 3.0.8 on 2020-07-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='friday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='friday_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='friday_time_block',
            field=models.CharField(choices=[('1', '1 hr'), ('1.5', '1.5 hrs'), ('2', '2 hrs')], max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='monday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='monday_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='monday_time_block',
            field=models.CharField(choices=[('1', '1 hr'), ('1.5', '1.5 hrs'), ('2', '2 hrs')], max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='saturday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='saturday_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='saturday_time_block',
            field=models.CharField(choices=[('1', '1 hr'), ('1.5', '1.5 hrs'), ('2', '2 hrs')], max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sunday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sunday_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sunday_time_block',
            field=models.CharField(choices=[('1', '1 hr'), ('1.5', '1.5 hrs'), ('2', '2 hrs')], max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='thursday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='thursday_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='thursday_time_block',
            field=models.CharField(choices=[('1', '1 hr'), ('1.5', '1.5 hrs'), ('2', '2 hrs')], max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tuesday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tuesday_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tuesday_time_block',
            field=models.CharField(choices=[('1', '1 hr'), ('1.5', '1.5 hrs'), ('2', '2 hrs')], max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='wednesday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='wednesday_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='wednesday_time_block',
            field=models.CharField(choices=[('1', '1 hr'), ('1.5', '1.5 hrs'), ('2', '2 hrs')], max_length=5),
        ),
    ]
