# Generated by Django 3.0.8 on 2020-07-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200713_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='friday_time_block',
            field=models.CharField(blank=True, choices=[('1', '1 hr'), ('1.5', '1.5 hrs'), ('2', '2 hrs')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='monday_time_block',
            field=models.CharField(blank=True, choices=[('1', '1 hr'), ('1.5', '1.5 hrs'), ('2', '2 hrs')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='saturday_time_block',
            field=models.CharField(blank=True, choices=[('1', '1 hr'), ('1.5', '1.5 hrs'), ('2', '2 hrs')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sunday_time_block',
            field=models.CharField(blank=True, choices=[('1', '1 hr'), ('1.5', '1.5 hrs'), ('2', '2 hrs')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='thursday_time_block',
            field=models.CharField(blank=True, choices=[('1', '1 hr'), ('1.5', '1.5 hrs'), ('2', '2 hrs')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tuesday_time_block',
            field=models.CharField(blank=True, choices=[('1', '1 hr'), ('1.5', '1.5 hrs'), ('2', '2 hrs')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='wednesday_time_block',
            field=models.CharField(blank=True, choices=[('1', '1 hr'), ('1.5', '1.5 hrs'), ('2', '2 hrs')], max_length=5, null=True),
        ),
    ]
