# Generated by Django 3.0.8 on 2020-07-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200713_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='haricut_teen',
            new_name='beard_trim',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='service',
        ),
        migrations.AddField(
            model_name='reservation',
            name='service',
            field=models.ManyToManyField(related_name='service_res', to='shop.Service'),
        ),
    ]
