# Generated by Django 3.0.8 on 2020-07-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200714_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='beard_trim',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='service',
            name='haircut_adult',
        ),
        migrations.RemoveField(
            model_name='service',
            name='haircut_child',
        ),
        migrations.RemoveField(
            model_name='service',
            name='shave',
        ),
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(default='blank', max_length=255),
            preserve_default=False,
        ),
    ]
