# Generated by Django 3.2.3 on 2021-06-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200716_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='recieve_updates',
            field=models.BooleanField(default=False),
        ),
    ]
