# Generated by Django 3.2.4 on 2021-06-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_customer_recieve_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='recieve_updates',
            field=models.BooleanField(default=True),
        ),
    ]
